__all__ = [
    "SCREEN_WIDTH",
    "SCREEN_HEIGHT",
    "ASTEROID_MIN_RADIUS",
    "ASTEROID_KINDS",
    "ASTEROID_SPAWN_RATE",
    "ASTEROID_MAX_RADIUS",
    "PLAYER_RADIUS",
    "PLAYER_TURN_SPEED",
    "PLAYER_SPEED",
    "PLAYER_SHOT_SPEED",
]

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 250
PLAYER_SHOT_SPEED = 400
